### ISSUE TITLE
Have one set of "ok/cancel" buttons for the entire dialog, not one for each tab

### ISSUE THREAD

**Issue by BlueRaja** [andrewgu/ModConfigMenu#13]
Right now each settings tab can specify which set of buttons to use.  Each tab is expected to keep track of config changes using change-handlers.

This has a number of issues:
1. It leads to an inconsistent user experience between tabs, making the config menus harder to use.
2. It is inconsistent with the conventional way settings dialogs work, in both [Windows](https://www.google.com/search?q=windows+settings+dialog&tbm=isch) and [Mac](https://www.google.com/search?q=mac+settings+dialog&tbm=isch)
3. It is inconsistent with the way the XCOM 2 settings dialog works
4. In order to implement "cancel", developers need to keep track of the initial values of every variable, which is a pain.  We could add this as a value to the controls _(and maybe still should)_, but there is a better way.

Here is my suggestion:
1. A single set of "Ok" and "Cancel" buttons, which do exactly as you'd expect.  We could also have "apply" and "restore defaults" on a per-tab basis.  Here is an example from Eclipse:
   
   ![Eclipse settings](http://infocenter.arm.com/help/topic/com.arm.doc.dui0480l/graphics/properties_dialog.png)
2. We ask developers _not_ to set values in change-handlers, and instead provide an `OnSave()` callback, which is called on every tab when 'OK' is clicked _(or on individual tabs when 'Apply' is clicked)_.  In this callback, they will apply their settings using a series of `MyConfigVar = MyControl.GetValue()` calls.  When can call `SaveConfig()` for them afterwards.
   
   This combines the small code-footprint of @Superd22's [`Default*Callback` suggestion](https://github.com/andrewgu/ModConfigMenu/pull/11#issuecomment-195727683) with the compile-time safety of using change-handlers.
   
   It also makes implementing 'Cancel' trivial. When cancel is clicked, we simply do nothing.

**Comment by Superd22** [comment]
Related to #6, MCM should definitely handle cancellation and restore to defaults, so :+1: 
As i advocated in #6, i think it should recognize new settings (as in settings that weren't there last time MCM was activated) and when default settings changed (as in when a mod did a update that changed the default value of a setting that the user had previously customized).

All of this is feasible via ini storing.

Side note : We're starting to have a few overlapping issues, so once we're all happy as to where we're going we should think about creating a clear roadmap and merging duplicates.

**Comment by BlueRaja** [comment]
What benefit does recognizing new settings or changed defaults give?
1. New settings are currently handled basically for free.
2. The only time the API should even care what the default is is when "restore defaults" is clicked. The only thing it needs to do is `CurrentValue = DefaultValue` for every control.

**Comment by Superd22** [comment]
It's all UI and end-user wise.

As a modder, i care about how my mod will function. To this day, updating a workshop mod will overwrite user settings unless the modder used a Default ini. Obviously in the documentation of MCM we will encourage people using MCM to migrate to that form of setting declaration.

Which means when a mod is updated with new features (and new settings) the custom config of the user will persist. This _will_ (and already does) break thing. 

"Oh, mod A v1.0 had a setting 1 that could range from 0 to 10 and was at 8 default in last update, so i was custom at 10. Turns out mod A V1.1 changed the way things are handled, and the default of this setting 1 is now 7, and turns out max is now 8.
I had no idea because patch logs are a mess either on the workshop or on the nexus, so i spent 20h+ looking through my 3409mods to find out which one was causing the issue i was having.

Man do i wish there was an easy way to see that the default value of a setting has changed since last update."

"Oh, Mod B v1.0 didn't have an option to do the thing i wanted to do, so i did a custom config as a workaround to that. Turns out Mod B V1.1 added said option. If only my MCM could highlight such new settings for me to find so i know something has changed and can decide whether or not i wanna do something about it."

I'm not suggesting we become a "patch-log hub", but having released a couple mods already, those are all stories i heard before and wished could be addressed. 

Let me stress that this does not add any hassle on the user declaring a new mod to MCM. All the logic should and can be handled by MCM alone.

**Comment by andrewgu** [comment]
@Superd22 I'm inclined to push off implicit handling of defaults and saving into a V2 extension if we do it at all. The reason is that as long as MCM is an optional mod, the code to persist settings may or may not exist, so if your mod still has to work without MCM installed, I would rather just make the mod author do it himself/herself in the first place. 

If we make it a mandatory dependency, I could see a better argument for internalizing the changes.

Good point on the notification of changes though. How feasible is it to add the alert icon to a setting the way it happens in the Armor menus?

**Comment by Superd22** [comment]
> add the alert icon to a setting the way it happens in the Armor menus?

Very easy.

> I'm inclined to push off implicit handling of defaults and saving into a V2 extension if we do it at all.

This change can be made long-term, i'm not saying we should make this a priority. However i do see a way to build this without requiring _ANY_ changes to the current API.

Simply add a config array containing, for each setting of each mod type, label name and default.
Store this array inside a MCM config file.

When the modder calls "DisplaySetting" simply get this array, and compare what was declared with what was in the config previously.

There is not a single line to change to the api nor any extra steps for the modder nor will it break anything if the users uninstalls MCM.
It is only a "dummy memory" used to change the UI whenever there's a new setting/default change.

All the logic is that way hidden from the modder.

**Comment by andrewgu** [comment]
This is now exactly how it works.
