### ISSUE TITLE
UISlider unable to show incremental values when stepsize is significantly smaller than 1/100 of range.

### ISSUE THREAD

**Issue by Neon3333** [andrewgu/ModConfigMenu#50]
Hello @andrewgu. I'm the author of the [Additional Difficulty Adjustment](http://steamcommunity.com/sharedfiles/filedetails/?id=913032920) mod. 

I encounter a bug in your mod.

In my mod I create a slider for parameter "HP Multiplier":

Group.AddSlider('SliderHPMultiplier', "HP Multiplier", "The coefficient applied to the points of health of enemies.", 0.0, 10.0, 0.05, HP_MULTIPLIER, SaveHandler_HPMultiplier);

Initial value is 1.00.

When I click right arrow button the value change as follows:

1, 1, 1.1, 1.15, 1.15, 1.25, 1.25, 1.35

But the parameter should change as follows:

1, 1.05, 1.1, 1.15, 1.2, 1.25, 1.3, 1.35

How to achieve an accurate setting of the value by the slider?

**Comment by andrewgu** [comment]
The default display algorithm is supposed to work "well enough for most cases," but due to limitations with how floating point numbers and the sliders work, it has some small issues that you can work around with a bit of extra code to customize how the slider shows numbers. I built it into the API anticipating that this issue would come up for some people.

Let me try debugging your mod and I'll get back to you.

**Comment by Neon3333** [comment]
Here is the source code of my mod:

[https://www.dropbox.com/s/2vanmgyi0wgwn96/Additional%20Difficulty%20Adjustment.zip?dl=0](https://www.dropbox.com/s/2vanmgyi0wgwn96/Additional%20Difficulty%20Adjustment.zip?dl=0)

**Comment by buinsky** [comment]
@andrewgu Are there any progress?

**Comment by Neon3333** [comment]
@andrewgu Are there any progress?

**Comment by andrewgu** [comment]
@Neon3333 Hey Neon, sorry for the delay and thanks for the reminder.

You ran into a bug I honestly hadn't thought about, but chances of fixing it are also pretty slim unless someone is willing to rewrite the slider control. The UISlider control has some quirks that will make the left and right arrows behave weirdly if the step size is less than 1/100th of the range. In your case, increments of 0.05 and limits of 0 to 10 means that the step size is 1/200 of the range. 

When the step size is too small, the Flash based slider control internally remembers the smaller increments, but the UISlider object doesn't give you a useful way to actually pull that granularity back out. That's why MCM seems to be giving you wrong numbers half of the time but is still respecting the increments overall.

My recommendation would be to switch to some way of keeping the step size at or above 1/100th of the range, maybe by switching to increments of 0.1, dropping the max from 10 to 5, or something fancier like a logarithmic slider to give players more resolution around 1.0 and less when they get closer to 10.

**Comment by Neon3333** [comment]
@andrewgu Thank you for your response.

I solved the issue by using integers (fractional numbers are multiplied by 100) and setting custom display filter for sliders for converting integers into fractional numbers.

**Comment by andrewgu** [comment]
Closing - won't fix for the foreseeable future.
