### ISSUE TITLE
Crashes at Startup

### ISSUE THREAD

**Issue by jg-development** [andrewgu/ModConfigMenu#52]
Hi,
I use the "Mod Config Menu Legacy" Version with Xcom2 Original (no dlc,wotc, etc).
My aim is Grimys Loot Mod + Legacy Mod Everything Reloaded and Mod Config Menu Legacy.
But with only the Mod Config Menu Legacy enabled the game crashes at startup.
I even uninstalled all mods (deleted all files) and used only Mod Config Menu Legacy, but the game still crashes.
Is the current legacy version compatible with standard xcom2?
I have the crash dump files if needed.
Thanks Jan

**Comment by boycad** [comment]
I use the "Legacy MCM" mod with LW2, and it was working as expected two nights ago.Verify, re-download / re-subscribe, clear configs...?mb~e.prinFrom: "Jan Gantzert" <notifications@github.com>To: "andrewgu/ModConfigMenu" <ModConfigMenu@noreply.github.com>CC: "Subscribed" <subscribed@noreply.github.com>Sent: 8 November, 2017 3:21 PMSubject: [andrewgu/ModConfigMenu] Crashes at Startup (#52)Hi,
I use the "Mod Config Menu Legacy" Version with Xcom2 Original (no dlc,wotc, etc).
My aim is Grimys Loot Mod + Legacy Mod Everything Reloaded and Mod Config Menu Legacy.
But with only the Mod Config Menu Legacy enabled the game crashes at startup.
I even uninstalled all mods (deleted all files) and used only Mod Config Menu Legacy, but the game still crashes.
Is the current legacy version compatible with standard xcom2?
I have the crash dump files if needed.
Thanks Jan

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/andrewgu/ModConfigMenu","title":"andrewgu/ModConfigMenu","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/andrewgu/ModConfigMenu"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Crashes at Startup (#52)"}],"action":{"name":"View Issue","url":"https://github.com/andrewgu/ModConfigMenu/issues/52"}}}

**Comment by jg-development** [comment]
Ok i did the hardcore method. desubscribed everything, wiped all data and uninstalled the game + deleting all files.
than installed xcom2 and only this mod ..... tadaaaa .... it works.
hmmm maybe the game uninstall mods not correct
Thanks for the quick response
