### ISSUE TITLE
Each control should be its own class

### ISSUE THREAD

**Issue by BlueRaja** [andrewgu/ModConfigMenu#9]
Right now each control is hard-coded into the control class, and to specify a control type you need to call [`InitAsSomeControlType()`](https://github.com/andrewgu/ModConfigMenu/blob/master/ModConfigMenu/ModConfigMenu/Src/ModConfigMenu/Classes/MCM_SettingItem.uc#L56).

If we break each control out into a different class, not only will the code be much cleaner, but it will be much easier for users to create their own controls, as well as for us to add new control-types in the future.

On the downside, it will require us to include more interfaces in the `ModConfigMenuAPI` folder.

**Comment by andrewgu** [comment]
Yup, that was the alternative design I was thinking about. So MCM_API_SettingsPage would have calls like "AddSlider" or "AddDropdown". They could return different interfaces, even if under the hood they're all UIMechaListItem derivatives. What do you think?

**Comment by Superd22** [comment]
Seems like a great occasion to get rid of `function array<MCM_API_Setting> MakeSettings(array<name> SettingNames);` and both the arrays coming alone.

and instead simply go 

```
MCM_API_SettingsPage.AddDropdown();
MCM_API_SettingsPage.AddSlider();
[...]
MCM_API_SettingsPage.DoneWithSettings();
```

As long as each class either a/ Extends a base class or b/ implements the same base interface (ie as long as we can still put all our settings in an array to iterate over) that's just great.

The ModConfigMenuAPI is not supposed to be tampered with, so i don't think the risk increases whether there's 1 or 20 files in it.

**Comment by BlueRaja** [comment]
Calling `DoneWithSettings()` shouldn't be necessary.  If we want to restrict users to only adding controls at a certain point or want to know when they're done, we should provide an `Initialize` event that we require them to handle and add all their controls in.

**Comment by Superd22** [comment]
My bad, it's not necessary for multiple classes.
It is only necessary if we wanna get ride of the array<name> we use to initilalize because we need to Spawn settings from bottom to top (bug with vanilla xcom2).

But it would be heavily tied with a multiple class refactor so might aswell include it.

**Comment by andrewgu** [comment]
DoneWithSettings() would still be necessary because of the bottom to top bug, unless we find a different way to determine the ordering after the fact. 

For every AddDropdown, as long as there is another setting above it, that setting must be added _after_ the dropdown. However, without DoneWithSettings, you wouldn't know that it'd be safe to actually place the most recent Add\* call.

**Comment by BlueRaja** [comment]
Whatever you are doing in `DoneWithSettings`, just do it after the `Initialize` callbacks are called.

**Comment by andrewgu** [comment]
Closing this one. The `InitAsSomeControlType()` pattern has been implemented. Going to open a separate issue about removing `MCM_API_SettingsPage.ShowSettings()` because it's not clear how exactly to instrument "after Initialize callbacks are called". When that's figured out, we can just make `ShowSettings()` a no-op and deprecate its usage in all future API versions.
